import "./globals.css";
import config from "react-reveal/globals";

config({ ssrFadeout: true });

export const metadata = {
  title: "Spotmies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
